
services:
  # Radarr - https://hotio.dev/containers/sonarr/
  sonarr:
    container_name: sonarr 
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped    
    pull_policy: always
    # Port will be proxied by nginx, so no need to expose it here
    # ports:
    #   - 8989:8989 
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ./sonarr:/config
      - ${ENTERTAINMENT_DIR}:/data
    networks:
      - frontend

networks:
  frontend:
    external: true