
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:1.10.6
    container_name: obsidian
    restart: 'unless-stopped'
    pull_policy: always
    env_file: .env
    volumes:
      - ${CONFIG_PATH}/obsidian/config:/config
    # Port will be proxied by traefik, so no need to expose it here
    # ports:
    #   - 3000:3000 # Obsidian desktop gui HTTP, must be proxied.
    #   - 3001:3001 # Obsidian desktop gui HTTPS.
    networks:
      - frontend
    labels:
      - "traefik.http.routers.obsidian.rule=Host(`obsidian.rlgland.site`)"
      - "traefik.http.routers.obsidian.entrypoints=websecure"
      - "traefik.http.routers.obsidian.tls.certresolver=cloudflare"
      - "traefik.http.services.obsidian.loadbalancer.server.port=3000"
    shm_size: "1gb"

networks:
  frontend:
    external: true
